version: 0.2

phases:
  install:
    commands:
      - echo "Hello, World! (phase=install)"
  pre_build:
    commands:
      - echo "Hello, World! (phase=pre_build)"
  build:
    commands:
<<<<<<< HEAD
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/messageUtil-1.0.jar
    - appspec.yml
  discard-paths: yes
=======
      - echo "Hello, World! (phase=build)"
      - ls -al
  post_build:
    commands:
      - echo "Hello, World! (phase=post_build)"
>>>>>>> 88d67d65b4bedb481501c4a1b0ac8cbdc0d1c8d3
